---
azure_vm_name: rhel93-01
azure_vm_user: wmarx
azure_vm_user_password: redhat123!
#azure_vm_image:
#  offer: RHEL
#  publisher: RedHat
#  sku: 8-LVM
#  version: latest
#azure_vm_size: Standard_A1_v2
#azure_bastion_vm_size: Standard_A1_v2
#azure_number_vm: 3

# PostgreSQL Server variables
azure_postgresql_name: "{{ azure_resource_group | replace('_', '-') }}-dbserver"
azure_postgresql_admin_username: ansible
azure_postgresql_admin_password: 4fB5In3ueO7,
azure_postgresql_database_instances:
  - name: pyapp
    charset: UTF8
azure_postgresql_firewall_rules:
  - name: allow_all
    start_ip_address: 0.0.0.0
    end_ip_address: 255.255.255.255

# Application variables
py_application:
  env: development
  admin_user: admin
  admin_password: admin
  docker_image: pywebapp
  docker_dir: /app/pyapp
  data_dir: /tmp/myapp_data
  container_name: myapp-container

application_force_init: false

application_src: https://github.com/abikouo/webapp_pyflask_demo.git

playbook_number_forks: 15
