---
azure_vm_name: rhel93-01
azure_vm_user: wmarx
azure_vm_user_password: redhat123!
#azure_vm_image:
#  offer: RHEL
#  publisher: RedHat
#  sku: 8-LVM
#  version: latest
#azure_vm_size: Standard_A1_v2
#azure_bastion_vm_size: Standard_A1_v2
#azure_number_vm: 3

# PostgreSQL Server variables
azure_postgresql_name: "{{ azure_resource_group | replace('_', '-') }}-dbserver"
azure_postgresql_admin_username: ansible
azure_postgresql_admin_password: 4fB5In3ueO7,
azure_postgresql_database_instances:
  - name: pyapp
    charset: UTF8
azure_postgresql_firewall_rules:
  - name: allow_all
    start_ip_address: 0.0.0.0
    end_ip_address: 255.255.255.255

# Application variables
py_application:
  env: development
  admin_user: admin
  admin_password: admin
  docker_image: pywebapp
  docker_dir: /app/pyapp
  data_dir: /tmp/myapp_data
  container_name: myapp-container

application_force_init: false

application_src: https://github.com/abikouo/webapp_pyflask_demo.git

playbook_number_forks: 15

# Sonstiges
resource_group_name: azure-demo
region: eastus
vnet_cidr: 10.0.0.0/16
subnet_cidr: 10.0.1.0/24
vnet_name: demo_vnet
subnet_name: demo_subnet
network_sec_group_name: linux_sec_group
linux_vm_name: rhel93-01
linux_vm_name1: rhel93-02
linux_vm_size: Standard_DS1_v2
win_public_ip: win_ip
win_public_ip_name: win_ip1
linux_public_ip_name: linux_public_ip
linux_public_ip_name1: linux1_public_ip
linux_nic_name: rhel01_demo_nic
linux1_nic_name: rhel02_demo_nic
win_nic_name: win_nic
linux_admin_user: wmarx
linux_admin_password: redhat123!
linux_vm_sku: 9-lvm-gen2
offer_rhel: RHEL
publisher_redhat: redhat
path_public_key: /home/wmarx/.ssh/authorized_keys
public_ssh_key: >-
  ssh-rsa
  AAAAB3NzaC1yc2EAAAADAQABAAABAQCdFRMQVARy5txGGcFB9+39bkoVSbYVGZxOKItQjbI9i/jtlxlAqLIHdRbgJWvk5rl1hmDimSRgyoHaWU30yClbgqe3X830Viv1lMo71WAdXl/DnryDdLNMNIFryUQKH4o3Qlne01cVc8nI/wAMzwA3z0sMluYRwik+U0+DyS2nhyPpNFYhvrFMm02qikuxM3/c04l2Umt/d2kwNVt0ewTSlXo3NsP9/ic6KmzXMcuvt/248CRsHUzoRRBgbE9RjhntXeGFNHubPrj/AD5VPBGLO3oGCAX0rIkCD7nxQQLkGK4bUEOkT1x9APoWB//0oV5chijUFaYoPZIcbP+tHprR
disk_type: StandardSSD_LRS
api_version_name: latest
ms_terms_accepted: 'true'
os_version_azure: Linux
version_rhel: latest
started_the_vm: 'true'
open_ports_vm:
  - 22
  - 443
  - 80
