- hosts: localhost
  roles:
     - role: roles/azure_manage_postgresql
       azure_manage_postgresql_operation: "create"
       azure_manage_postgresql_region: "eastus"
       azure_manage_postgresql_resource_group: "postgresql-rg"
       azure_manage_postgresql_postgresql_backup_retention_days: 3
       azure_manage_postgresql_postgresql_admin_username: admin
       azure_manage_postgresql_postgresql_admin_password: redhat123!
       azure_manage_postgresql_resource_group: azure-demo
       azure_manage_postgresql_postgresql_storage_mb: 506895
       azure_manage_postgresql_postgresql_name: "dbpostgresqldemo"
       
       azure_manage_postgresql_postgresql_sku:
          name: B_Gen5_1
          tier: Basic
       azure_manage_postgresql_resource_group_tags:
          tag0: "tag0"
          tag1: "tag1"
       azure_manage_postgresql_postgresql_settings:
          - name: deadlock_timeout
            value: 2000
       azure_manage_postgresql_postgresql_firewall_rule:
          - name: rule_0
            start_ip_address: 172.10.1.0
            end_ip_address: 172.10.128.0
