---
- name: Remove lock on the resource group
  when:
    - azure_manage_resource_group_force_delete_locked is defined
    - azure_manage_resource_group_force_delete_locked | bool
  block:
    - name: Get lock info for the resource group
      azure.azcollection.azure_rm_lock_info:
        resource_group: "{{ azure_manage_resource_group_name }}"
      register: result

    - name: Delete locks for the resource group
      azure.azcollection.azure_rm_lock:
        state: absent
        name: "{{ item.name }}"
        resource_group: "{{ azure_manage_resource_group_name }}"
      with_items: "{{ result.locks }}"

- name: Delete resource group
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ azure_manage_resource_group_name }}"
    state: absent
    force_delete_nonempty: "{{ azure_manage_resource_group_force_delete_nonempty | default(omit) }}"
