---
- name: Delete resource group
  ansible.builtin.import_role:
    name: cloud.azure_ops.azure_manage_resource_group
  vars:
    azure_manage_resource_group_operation: delete
    azure_manage_resource_group_name: "{{ azure_manage_networking_stack_resource_group }}"
    azure_manage_resource_group_force_delete_nonempty: true
    azure_manage_resource_group_force_delete_locked: true
  when: azure_manage_networking_stack_delete_option == 'all'

- name: Delete virtual network
  azure.azcollection.azure_rm_virtualnetwork:
    state: absent
    resource_group: "{{ azure_manage_networking_stack_resource_group }}"
    name: "{{ azure_manage_networking_stack_virtual_network }}"
  when: azure_manage_networking_stack_delete_option == 'virtual_network'

- name: Delete subnet
  azure.azcollection.azure_rm_subnet:
    state: absent
    resource_group: "{{ azure_manage_networking_stack_resource_group }}"
    virtual_network: "{{ azure_manage_networking_stack_virtual_network }}"
    name: "{{ azure_manage_networking_stack_subnet }}"
  when: azure_manage_networking_stack_delete_option == 'subnet'
